############################################################################################
#
#    ____ _ _            _     ____             
#   / ___| (_) ___ _ __ | |_  |  _ \  _____   __
#  | |   | | |/ _ \ '_ \| __| | | | |/ _ \ \ / /
#  | |___| | |  __/ | | | |_  | |_| |  __/\ V / 
#   \____|_|_|\___|_| |_|\__| |____/ \___| \_/                            
#
# CLIENT DEV
#
# https://github.com/ayfantis53/mern-memories/blob/master/client/Dockerfile.dev

############################################################################################
# Node Building Layer
# This is a MINIMAL RUNTIME image to run Node project
# For testing Memories frontend locally
############################################################################################

# Use the official Node.js runtime as the parent image.
# This provides the necessary environment to run a Node.js application.
FROM node:latest

# Set the working directory inside the container.
# All subsequent commands (COPY, RUN, CMD) will be executed relative to this directory.
WORKDIR '/app'

# Copy package.json and package-lock.json (if present) from the host to the container's working directory.
# This allows npm install to leverage layer caching effectively.
COPY ./package*.json ./

# Install project dependencies.
# This command runs after copying the package files to a new layer.
# The output of this command (node_modules directory) will be cached unless package*.json changes.
RUN npm install

# Copy the rest of the application source code from the host to the container's working directory.
# The previously created node_modules directory will remain intact.
COPY . .

# Specify the command to run when the container starts.
# The exec form of CMD is used (JSON array), which runs the command directly without a shell.
# This ensures that the application is the primary process of the container.
CMD ["npm", "run", "start"]