# ================================================================================== # 
#                                 ** WEBAPP-SECRET **                                #
# ================================================================================== #
apiVersion: v1                  # Specifies the Kubernetes API version to use. "v1" is standard for Secret objects.
kind: Secret                    # Declares the type of Kubernetes object being created.
metadata:                       # provides information about the resource, such as its name and optional annotations/labels.
  name: webapp-secret           # A unique name for the secret within the namespace.
type: Opaque                    # Specifies the type of secret. "Opaque" is for arbitrary user-defined data.
data:                           # The 'data' field stores the sensitive information as Base64 encoded key-value pairs.
  DBPASSWORD: bW9uZ29kYitzcnY6Ly9heWZhbnRpczUzOkFuZDNmbGlwJTIzQG1lcm4ueXc3aWRweC5tb25nb2RiLm5ldC9tZW1vcmllcz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  GOOGLECLIENTPASSWORD: MTc4MTkzNzQwNDMxLTRnbzc5dGsxYnMxNG03MGZibmE0M2E0aWN1ZGNndGI0LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t