apiVersion: v1
kind: Secret
metadata: 
  name: app-secrets
type: Opaque
data:
  DBPASSWORD: bW9uZ29kYitzcnY6Ly9heWZhbnRpczUzOkFuZDNmbGlwJTIzQG1lcm4ueXc3aWRweC5tb25nb2RiLm5ldC9tZW1vcmllcz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  GOOGLECLIENTPASSWORD: MTc4MTkzNzQwNDMxLTRnbzc5dGsxYnMxNG03MGZibmE0M2E0aWN1ZGNndGI0LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t