############################################################################################
#
#   ____                             ____             
#  / ___|  ___ _ ____   _____ _ __  |  _ \  _____   __
#  \___ \ / _ \ '__\ \ / / _ \ '__| | | | |/ _ \ \ / /
#   ___) |  __/ |   \ V /  __/ |    | |_| |  __/\ V / 
#  |____/ \___|_|    \_/ \___|_|    |____/ \___| \_/                               
#
# SERVER DEV
#
# https://github.com/ayfantis53/mern-memories/blob/master/client/Dockerfile.dev

############################################################################################
# Node Building Layer
# This is a MINIMAL RUNTIME image to run Node project
# For building Memories app backend locally
############################################################################################

# Use Node image as base layer
FROM node:latest

# Create app directory
WORKDIR '/app'

# Install app dependencies
COPY ./package*.json ./
RUN npm install

# Bundle app source
COPY . .

# run app
CMD ["npm", "run", "build"]
