# This configuration ensures that requests to the NGINX proxy are forwarded to the backend service.
upstream client {             # Creates a named group of servers (a "cluster") called "client" to which requests can be proxied.
    server client:3000;       # Specifies that a backend application is running on a host named client and listening on port 3000.
}
# Often used in load balancing, where multiple server lines might exist, or just for reverse proxying to a containerized microservice.
upstream api {                # Creates a named group of servers (a "cluster") called "api" to which requests can be proxied.
    server api:5000;          # Defines a backend server in that group. It tells the proxy to send traffic to a service reachable at hostname api on port 5000.
}

# defines a Virtual Server block (or virtual host), which contains directives for handling specific HTTP requests.
server { 
    # Listens for incoming HTTP traffic on port 80.
    listen 80;

    # Forwards all traffic (root URL) to a server/container named client.
    location / {                      # Routes any request starting with / to a separate backend service
        proxy_pass http://client;     # Instructs Nginx to pass the incoming request to the specified server "upstream block: client".
    }

    # Handles WebSocket connections for real-time updates.
    location /ws {                                # Matches any request path starting with /ws
        proxy_pass http://client;                 # Forwards requests to the upstream group named client.
        proxy_http_version 1.1;                   # Required for WebSockets; tells NGINX to use HTTP/1.1 instead of the default 1.0, enabling persistent connections.
        proxy_set_header Upgrade $http_upgrade;   # Passes the Upgrade header from the client, indicating a desire to switch to a WebSocket connection.
        proxy_set_header Connection "Upgrade";    # Sets the Connection header to "Upgrade" to signal the protocol switch to the backend.
    }
    
    # API Proxy Configuration (assuming backend runs on port 5000)
    location /api {             # Routes any request starting with /api to a separate backend service
        proxy_pass http://api;  # Instructs Nginx to pass the incoming request to the specified server "upstream block: api".
  }
}
